# Generated by Django 3.2 on 2023-01-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hcs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('inquiry', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_catagory', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_catagory', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_url', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_catagory', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Scam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_catagory', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.entry')),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('crack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.crack')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.entry')),
                ('hack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.hack')),
                ('scam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.scam')),
                ('user', models.ForeignKey(on_delete=models.SET(hcs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crack',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcs.entry'),
        ),
    ]
